### PR TITLE
update aggregator section of getting started

### PR DESCRIPTION
**Pull request by tkmct**

### CODE REVIEW

**Comment by syuhei176** [comment]
@tkmct Should we change this line?
https://github.com/cryptoeconomicslab/ovm-plasma-chamber-spec/pull/15/files#diff-7a651bba2a3fb684047783ec701f71fdR47-R49

**Comment by tkmct** [comment]
Thank you. Fixed!

**Comment by syuhei176** [comment]
Oh, please also check line 48!

**Comment by tkmct** [comment]
sorry, fixed

**Pull request merged**
