### PR TITLE
add introduction

### PR DESCRIPTION
**Pull request by tkmct**

### CODE REVIEW

**Comment by daiki44** [comment]
@tkmct Wil you insert a diagram into this introduction?

**Comment by tkmct** [comment]
No I'm not for this moment.

**Comment by tkmct** [comment]
@daiki44 If you have some, please add them later.

**Comment by daiki44** [comment]
@tkmct ok. I will create it later.

**Comment by daiki44** [comment]
@tkmct 
Can you check this?
スクリーンショット 2020-04-22 19 20 19

**Comment by tkmct** [comment]
I think it's great!

**Pull request merged**
